//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Meisho
    {
        public string Meisho_Kbn { get; set; }
        public decimal Meisho_Cd { get; set; }
        public string Meisho { get; set; }
    }
}
