//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Shohin
    {
        public string Shohin_Cd { get; set; }
        public string Shohin_Name { get; set; }
        public string Tani { get; set; }
        public Nullable<decimal> Tanka { get; set; }
    }
}
