//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Tokui
    {
        public string Tokui_Cd { get; set; }
        public string Tokui_Name { get; set; }
        public string Tantosha_Cd { get; set; }
        public string Shiharai { get; set; }
        public string Yuko_Kigen { get; set; }
    }
}
