//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_User
    {
        public string User_Id { get; set; }
        public string User_Pass { get; set; }
        public string User_Name { get; set; }
    }
}
