//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Mitsu_B
    {
        public decimal Mitsu_No { get; set; }
        public decimal Gyo_No { get; set; }
        public string Shohin_Cd { get; set; }
        public Nullable<decimal> Suryo { get; set; }
        public string Tani { get; set; }
        public Nullable<decimal> Tanka { get; set; }
        public Nullable<decimal> Kingaku { get; set; }
    
        public virtual T_Mitsu_H T_Mitsu_H { get; set; }
    }
}
