//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Mitsu_H
    {
        public T_Mitsu_H()
        {
            this.T_Mitsu_B = new HashSet<T_Mitsu_B>();
        }
    
        public decimal Mitsu_No { get; set; }
        public decimal Mitsu_Date { get; set; }
        public string Tantosha_Cd { get; set; }
        public string Tokui_Cd { get; set; }
        public string Yoken { get; set; }
        public string Shiharai { get; set; }
        public string Yuko_Kigen { get; set; }
    
        public virtual ICollection<T_Mitsu_B> T_Mitsu_B { get; set; }
    }
}
