//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialData.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrialEntities : DbContext
    {
        public TrialEntities()
            : base("name=TrialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_Meisho> M_Meisho { get; set; }
        public virtual DbSet<M_Shohin> M_Shohin { get; set; }
        public virtual DbSet<M_Tokui> M_Tokui { get; set; }
        public virtual DbSet<M_User> M_User { get; set; }
        public virtual DbSet<T_Mitsu_B> T_Mitsu_B { get; set; }
        public virtual DbSet<T_Mitsu_H> T_Mitsu_H { get; set; }
    }
}
